### ISSUE TITLE
micro-service com_app

### ISSUE THREAD

**Issue by AymanSaleh23** [AymanSaleh23/VehiclesTransparent#15]
Implement an application handle the outer communication task of the project using micro-service technique.

Use `com_socket.py` library to create sockets for sending and receiving discrete data of frames between ports/machines.

input:
- frame.
- discrete data.

output: 
- no output.

behavior:
- send frame and discrete data to another machine throw the Socket using our `com_socket.py` library

Use functions support that from the `Server` class:
- `update_to_send `for asynchronously send discrete data.
- `send_frames` for sending frames.

Use functions support that from the `Server` class:
- `receive_frame` for receiving frames from the `Server`.
- `recv_discrete` for receiving discrete data (list/dict/any type) from the `Server`.

**Comment by MoMagdy14** [comment]
- add data_transfer module (client, server, thread): this module is responsible for receiving data from the running modules on the front car and transmit to back car.
- running on a sperate thread.

**Comment by MoMagdy14** [comment]
yet, a test should be added.

**Comment by MoMagdy14** [comment]
add "Data Transmitter" a new implementation,
a class that creates a thread to receive data from different modules and serve them to requesters.
