### ISSUE TITLE
GUI front/back

### ISSUE THREAD

**Issue by AymanSaleh23** [AymanSaleh23/VehiclesTransparent#29]
Implement simple GUI application using any package supports:
- Button On (Activation)
- Fixed full screen resolution.
- when button is pressed activate the system.
- For instance, the same application for front and back.

**Comment by abdallaskar** [comment]
I'm add simple GUI using tkinter to fire system

**Comment by AymanSaleh23** [comment]
This is awesome,
The next step is try to hide the cursor when it overlabs the picture to make the screen more realistic.
That enables us to get rid of the button and substitute it with even like touch/click.

**Comment by abdallaskar** [comment]
I hid the mouse cursor and added event to system.
system can fire with any click mouse  button 
and delete the main button from the screen

**Comment by AymanSaleh23** [comment]
Good job.
This issue has been Done.
